config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pets#index"

  resources :pets do
    resources :bookings, only: %i[new create] do
      resources :reviews, only: %i[new create]
    end
  end
  resources :bookings, only: %i[destroy update]

  namespace :dashboard do
    get "/", to: "users#home"
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pet

  has_many :reviews, dependent: :destroy

  enum status: { pending: 0, confirmed: 1, rejected: 2 }

  validates :start_date, presence: true
  validates :end_date, presence: true

  validate :start_date_not_in_past
  validate :end_date_after_start_date

  private

  def start_date_not_in_past
    return if end_date.blank? || start_date.blank?
      if start_date <= Date.current
        errors.add(:start_date, "must be after today")
      end
  end

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?
      if end_date < start_date
        errors.add(:end_date, "must be after the start date")
      end
  end
end

app/models/pet.rb
class Pet < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :booking
  has_one_attached :photo # replace has_one_attached with has_many_attached if you want to upload multiple photos

  validates :name, presence: true
  validates :price, presence: true, comparison: { greater_than: 0 }
  validates :photo, presence: true
  validates :description, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  has_one :user, through: :booking
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :pets
  has_one_attached :photo

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  geocoded_by :concat_address
  after_validation :geocode, if: :will_save_change_to_address?

  def concat_address
    [address, zipcode, city].compact.join(', ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name address zipcode city])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name address zipcode city])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_pet, only: %i[new create]
  skip_before_action :verify_authenticity_token, only: %i[update]

  def new
    @booking = Booking.new
  end

  def create
    dates = params[:booking][:start_date].split(" to ")
    start_date = dates.first
    end_date = dates.last
    @booking = Booking.new(start_date: start_date, end_date: end_date)
    @booking.pet = @pet
    @booking.user = current_user
    if @booking.save
      flash.alert = "Your reservation is pending! Wait for owner to confirm :)"
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    booking = Booking.find(params[:id])
    booking.status = params[:status]
    respond_to_booking_update(booking) if booking.update(booking_params)
  end

  private

  def respond_to_booking_update(booking)
    respond_to do |format|
      format.json do
        render json: {
          new_status: booking.status
        }
      end
    end
  end

  def set_pet
    @pet = Pet.find(params[:pet_id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/controllers/dashboard/users_controller.rb
module Dashboard
  class UsersController < ApplicationController
    def home
      pets_with_bookings = current_user.pets.select do |pet|
        pet.bookings.any?
      end
      @my_pet_bookings = make_my_pet_bookings(pets_with_bookings)

      @my_bookings = make_my_bookings(current_user.bookings)

      @pet = Pet.new
    end

    private

    def make_my_pet_bookings(pets)
      pets.map do |pet|
        {
          pet:,
          booking: pet.bookings.first,
          total_price: pet.price * (pet.bookings.first.end_date - pet.bookings.first.start_date).to_i
        }
      end
    end

    def make_my_bookings(bookings)
      bookings.map do |booking|
        {
          booking:,
          pet: booking.pet,
          total_price: booking.pet.price * (booking.end_date - booking.start_date).to_i
        }
      end
    end
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: %i[edit update destroy]
  skip_before_action :authenticate_user!, only: :index

  def index
    @pets = Pet.all
    @markers = @pets.map do |pet|
      {
        lat: pet.user.latitude,
        lng: pet.user.longitude,
        marker_html: render_to_string(partial: "map_marker")
      }
    end
  end

  def show
    pets = Pet.where(id: params[:id]) # collection // array
    if pets.empty?
      flash.alert = "This pet doesn't exist!"
      redirect_to :root
    else
      @pet = pets[0]
    end
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.user = current_user
    if @pet.save
      redirect_to pet_path(@pet)
      flash.alert = "Chiot ajouté :)"
    else
      redirect_to dashboard_path
      flash.alert = "Information manquante, impossible d'ajouter un chiot :("
    end
  end

  def edit
  end

  def update
    if @pet.update(pet_params)
      redirect_to dashboard_path, notice: 'Ton Pet est bien modifié !'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @pet.destroy
    redirect_to dashboard_path, notice: 'Ton Pet est supprimé!', status: :see_other
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :species, :price, :photo, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_pet, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.pet = @pet
    if @review.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_pet
    @pet = Pet.find(params[:pet_id])
  end

  def review_params
    params.require(:review).permit(:message, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<h1>New Booking</h1>
<div class="w-50 mx-auto">

  <%= simple_form_for [pet, booking] do |f| %>
    <div class="form-inputs">
      <%= f.input :start_date %>
      <%= f.input :end_date %>
    </div>

   <div class="form-actions">
      <%= f.submit "Book !", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/bookings/new.html.erb
<%= render partial: "form", locals: { pet: @pet, booking: @booking } %>

app/views/dashboard/users/_booking.html.erb
<div data-controller="booking-confirmation" data-booking-confirmation-booking-value="<%= booking[:booking].id %>" class="p-2 rounded">
  <%= render partial: "shared/pet", locals: { pet: booking[:pet] } %>
  <div class="text-center">

  <p><%= booking[:booking][:start_date].strftime('%d %b \'%y') %> - <%= booking[:booking][:end_date].strftime('%d %b \'%y') %></p>
  <p>Total: <strong><%= booking[:total_price] %>€</strong></p>
  <p data-booking-confirmation-target="status">Status: <%= booking[:booking].status %></p>
  <% if booking[:booking].pet.user == current_user && booking[:booking].status == "pending" %>
    <div data-booking-confirmation-target="btns" class="d-flex justify-content-center gap-4">
      <button data-action="click->booking-confirmation#confirm" data-status="confirmed" class="btn btn-primary">Confirm</button>
      <button data-action="click->booking-confirmation#confirm" data-status="rejected" class="btn btn-warning">Decline</button>
    </div>
  <% end %>
  </div>
</div>

app/views/dashboard/users/home.html.erb
<h1 class="my-5">Welcome <%= current_user.first_name %></h1>

<h2>J'ai loué ces chiots</h2>
<% if current_user.bookings.any? %>
  <div class="d-flex flex-wrap gap-2 mb-5">
    <% @my_bookings.each do |booking| %>
      <%= render partial: "booking", locals: { booking: booking } %>
    <% end %>
  </div>
<% else %>
  <p>Tu n'as pas encore loué de chiot?</p>
<% end %>

<h2>Mes Chiots</h2>
<div class="row">
  <div class="col-md-8">
    <div class="d-flex justfiy-content-between gap-4">
      <h3>Tous mes chiots</h3>
      <div data-controller="new-pet">
        <button class="btn btn-primary mb-3" data-action="click->new-pet#toggleForm">Ajouter un chiot</button>
          <div class="d-none" data-new-pet-target="form">
            <%= simple_form_for @pet do |f| %>
              <div class="form-inputs mb-3"  >
                <%= f.input :name %>
                <%= f.input :price %>
                <%= f.input :description %>
                <%= f.input :photo, as: :file %>
                <%= f.submit "Youpi !", class: "btn btn-primary" %>
              </div>
            <% end %>
          </div>
      </div>
    </div>
    <% if current_user.pets.any? %>
      <div class="mb-5 d-flex flex-wrap gap-2">
        <% current_user.pets.each do |pet| %>
          <%= link_to render(
            partial: "shared/pet", locals: { pet: pet }
              ), pet %>
        <% end %>
      </div>
    <% else %>
      <p>Tu n'as encore aucun chiot !</p>
    <% end %>
  </div>

  <div class="col-md-4">
    <% if current_user.pets.any? %>
      <% if @my_pet_bookings.any? %>
        <h3>Gestion des réservations</h3>
        <div class="d-flex flex-wrap gap-2 mb-3">
          <% @my_pet_bookings.each do |booking| %>
            <%= render partial: "booking", locals: { booking: booking } %>
          <% end %>
        </div>
      <% else %>
        <p>Personne à loué ton chiot, il est pas assez mim's</p>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PuppyMatch</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <%= render "shared/flashes" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pets/_detailed_card.html.erb
<div class="glass w-100 mr-12 p-3 text-shadow ">
  <%= yield %>
</div>

app/views/pets/_form.html.erb
<%= simple_form_for @pet do |f| %>
  <div class="form-inputs mb-3"  >
    <%= f.input :name %>
    <%= f.input :price %>
    <%= f.input :description %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Youpi !", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pets/_map_marker.html.erb
<%= image_tag "paw.png", height: 30, width: 30, alt: "Paw" %>

app/views/pets/_pet.html.erb
  <%= simple_form_for @pet do |f| %>
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :price %>
      <%= f.input :species %>
      <%= f.input :photo, as: :file %>
      <%= f.submit "Youpi !", class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/pets/edit.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Edit my Pet</h1>
        <div class="mt-3">
          <%= render "form", pet: @pet %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pets/index.html.erb
<div class="d-flex">
  <div class="p-4">
    <div class="row" id="pets">
      <% @pets.each do |pet| %>
        <div class="col-xl-6">
          <%= link_to render(
            partial: "shared/pet", locals: { pet: pet }
          ), pet %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="d-none d-md-block">

  <div style="min-width: 500px; height: 100vh;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
  </div>
</div>

app/views/pets/new.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-6 m-auto">
      <div class="flat-form">
        <h1>Ajoute un chiot</h1>
        <div class="mt-3">
          <%= render "form", pet: @pet %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pets/show.html.erb
<div class="container mt-4">
    <!-- Pet Details -->
  <div class="d-flex gap-4 ">
    <div class="overflow-hidden rounded">
    <%= cl_image_tag @pet.photo.key, height: 800, width: 900, crop: :fill %>
    </div>
    <div class="d-flex flex-column justify-content-between gap-4">
      <%= render "detailed_card" do %>
        <h1>Hey coucou, I'm <strong><%= @pet.name %></strong></h1>
      <% end %>
      <%= render"detailed_card" do %>
        <div class= "p-2 border-bottom">
          <p><strong>Qui-suis-je ?</strong></p>
          <p><%= @pet.description %></p>
        </div>
        <div class= "p-2 border-bottom">
          <% if @pet.taux_de_succes > 0.0 %>
            <p><strong>Mon p'tit taux de succès 🍆 :</strong></p>
          <% end %>
          <p>Je vais booster ton potentiel de séduction 💘</p>
          <% if @pet.taux_de_succes > 0.0 %>
            <span>car grâce à moi <strong><%= @pet.taux_de_succes.round(1)%>%</strong> des pélo' ont pécho!</span>
          <% end %>
        </div>
        <div class= "p-2 d-flex justify-items-center">
          <div class="p-2 border-end" style="flex: 1;">
            <p><strong>J'habite à :</strong></p>
            <h5>🏠 <%= @pet.user.city.capitalize %>, <%= @pet.user.zipcode %></h5>
          </div>
          <div class="p-2" style="flex: 1;">
           <p><strong>Je suis le 🐶 doggy de : </strong></p>
           <h5> <%= @pet.user.first_name.capitalize %></h5>
          </div>
        </div>
      <% end %>
      <%= render "detailed_card" do %>
        <div>
            <h4><strong><%= @pet.price %>€ </strong>par jour</h4>
        </div>
        <div data-controller="price" data-price-price-value="<%= @pet.price %>">
          <%= simple_form_for [@pet, Booking.new] do |f| %>
            <%= f.input :start_date, label: 'Sélectionne tes dates !',
                as: :string,
                input_html: { data: { controller: "datepicker", action: "change->price#handleDateChange" } } %>
            <div class="form-actions d-flex justify-content-between align-items-baseline">
              <%= f.submit "Book !", class: "btn btn-warning disabled", data: { price_target: "btn" } %>
              <h4 data-price-target="total" class="me-4"></h4>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<%# Find me in app/views/reviews/new.html.erb %>

<h1>New review</h1>
<%= simple_form_for [@pet, @review] do |f| %>
  <%= f.input :message %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

<%# <%= link_to "back to home", root_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar shadow">
  <div class="container-fluid">
    <a class="navbar-brand fs-2 pb-2" href="/">Puppy Match</a>
    <% if user_signed_in? %>
      <div class="flex gap-4">
        <%= link_to "Dashboard", dashboard_path, class: "btn btn-outline-warning" %>
        <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "btn btn-outline-secondary" %>
      </div>
    <% else %>
      <%= link_to "Sign In", new_user_session_path %>
    <% end %>
  </div>
</nav>

app/views/shared/_pet.html.erb
<div class="card border-0 mb-3 overflow-hidden shadow" style="max-width: 350px; min-height:410px;">
    <%= cl_image_tag pet.photo.key, height: 250, width: 350, crop: :fill %>
  <div class="card-body d-flex flex-column justify-content-between">
    <div class="row d-flex align-item-center">
      <h5 class="card-title d-flex justify-content-between">
        <Strong><%= pet.name %></Strong>
          <span> 🍆 <%= pet.taux_de_succes.round(1)%>%</span>
      </h5>
      <p><%= truncate(pet.description, length: 60, separator: ' ', omission: ' (...)') %>
    </div>
    <div class="d-flex justify-content-between">
      <p><Strong><%= pet.price %>€</Strong> par jour</p>
      <% unless current_page?(root_path) %>
        <% if pet.user == current_user %>
          <div class="ms-2 d-flex gap-2">
            <%= link_to content_tag(:i, '', class: 'fas fa-edit link-primary'), edit_pet_path(pet) %>
            <%= link_to content_tag(:i,'',class: 'fas fa-trash-can  link-primary'), pet_path(pet),
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }
              %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>